name: go_campus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5        # State Management
  hive: ^2.2.3            # Local Database
  hive_flutter: ^1.1.0    # Hive helper
  geolocator: ^14.0.2     # GPS tracking
  flutter_local_notifications: ^21.0.0 # Alerts
  intl: ^0.20.2           # For formatting time/dates
  url_launcher: ^6.3.2    # Open Ride-Hailing App
  firebase_auth: ^6.4.0   # Database
  firebase_core: ^4.7.0  # Firebase initialization
  firebase_messaging: ^16.2.0  # For push notifications
  cloud_firestore: ^6.3.0  # For storing user data
  google_sign_in: ^7.2.0  # Google Sign-In
  geocoding: ^4.0.0       # Addresses
  flutter_svg: ^ 2.3.0     # For SVG icons
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logosplash.svg