// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuBOgWCc1A_wFQ-ygu2XX3HymiiG6KF0o',
    appId: '1:579758461412:web:73dbd720a411739344f7f1',
    messagingSenderId: '579758461412',
    projectId: 'myproject-d9d3f',
    authDomain: 'myproject-d9d3f.firebaseapp.com',
    databaseURL: 'https://myproject-d9d3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myproject-d9d3f.firebasestorage.app',
    measurementId: 'G-XDQMJ4QDW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4E2vIluudKcYkeqnLq-WtI58Bnd-6Fc',
    appId: '1:579758461412:android:0e7b83521a918f3844f7f1',
    messagingSenderId: '579758461412',
    projectId: 'myproject-d9d3f',
    databaseURL: 'https://myproject-d9d3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myproject-d9d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw63Qgap_WIy1sCStjFCa_GEoAUaSXY_s',
    appId: '1:579758461412:ios:52521d64e45db03144f7f1',
    messagingSenderId: '579758461412',
    projectId: 'myproject-d9d3f',
    databaseURL: 'https://myproject-d9d3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myproject-d9d3f.firebasestorage.app',
    iosBundleId: 'com.example.goCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw63Qgap_WIy1sCStjFCa_GEoAUaSXY_s',
    appId: '1:579758461412:ios:52521d64e45db03144f7f1',
    messagingSenderId: '579758461412',
    projectId: 'myproject-d9d3f',
    databaseURL: 'https://myproject-d9d3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myproject-d9d3f.firebasestorage.app',
    iosBundleId: 'com.example.goCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuBOgWCc1A_wFQ-ygu2XX3HymiiG6KF0o',
    appId: '1:579758461412:web:50a8cf11ab5fbb5644f7f1',
    messagingSenderId: '579758461412',
    projectId: 'myproject-d9d3f',
    authDomain: 'myproject-d9d3f.firebaseapp.com',
    databaseURL: 'https://myproject-d9d3f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myproject-d9d3f.firebasestorage.app',
    measurementId: 'G-XJJ0E8ENVG',
  );
}
