// main.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:firebase_core/firebase_core.dart'; // 1. Ensure this is imported
import 'firebase_options.dart'; // Generated by FlutterFire
import 'providers/user_provider.dart';
import 'providers/ride_provider.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = 
    FlutterLocalNotificationsPlugin();

void main() async {
  // MUST BE FIRST: Required for any async setup
  WidgetsFlutterBinding.ensureInitialized();

  // 2. INITIALIZE FIREBASE 
  // If you are using Firestore, this line MUST NOT be commented out.
  // If it's commented out, the RideProvider will crash the app silently.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  
  // Initialize Hive
  await Hive.initFlutter();

  // 3. START THE APP IMMEDIATELY (Principle #5: KISS)
  // We move the "data loading" logic inside the app build process
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => RideProvider()),
      ],
      child: const GoCampusApp(),
    ),
  );
}

class GoCampusApp extends StatelessWidget {
  const GoCampusApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GoCampus',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF3F51B5)),
      ),
      // Use a FutureBuilder to handle the "Wait" (Principle #14)
      home: const AuthGate(),
    );
  }
}

class AuthGate extends StatefulWidget {
  const AuthGate({super.key});

  @override
  State<AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<AuthGate> {
  late Future<void> _initFuture;

  @override
  void initState() {
    super.initState();
    // 4. PRE-FLIGHT CHECK: Load Hive and Setup Notifications while splash is visible
    _initFuture = _prepareApp();
  }

  Future<void> _prepareApp() async {
    final userProvider = context.read<UserProvider>();
    final rideProvider = context.read<RideProvider>();

    // Notification Setup
    const android = AndroidInitializationSettings('@mipmap/ic_launcher');
    await flutterLocalNotificationsPlugin.initialize(
      settings: const InitializationSettings(android: android),
    );

    // Load Data
    await userProvider.loadSession();
    await rideProvider.loadPools();
    rideProvider.startRealtimeSync();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _initFuture,
      builder: (context, snapshot) {
        // While waiting for Hive/Session to load, show a nice loading screen
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 10),
                  Text("Waking up GoCampus..."),
                ],
              ),
            ),
          );
        }

        // Once loaded, check login status
        final isLoggedIn = context.watch<UserProvider>().isLoggedIn;
        return isLoggedIn ? const HomeScreen() : const LoginScreen();
      },
    );
  }
}